### ISSUE TITLE
Improve renv workflow

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/rhino#101]
Modern "virtual environment" tools usually offer a single function to add a dependency to a project. For example, `yarn add` will install the package, add it to `project.json` and update `yarn.lock`.

With renv, the workflow consists of 3 separate steps: manually update `dependencies.R`, install package with `renv::install()`, update `renv.lock` with `renv::snapshot()`. This could be combined into a single step.

**Comment by Leszek-Sieminski** [comment]
One of the things that are great about Renv is that it doesn't break any existing functionalities or steps R programmers use. For example, Renv is using shims to "overwrite" `base::install.packages()` function with its own functionalities, so people using it will still use Renv under the hood.

I'm considering doing exactly the same - creating 2 Rhino shims (for `renv::install()` and `install.packages()`) that would have at least one additional step of automatically adding a dependency to `dependencies.R` (possibly also with some form of `renv::snapshot()` though this may be more complicated)
