### ISSUE TITLE
Don't require R session restart after `rhino::init()`

### ISSUE THREAD

**Issue by TymekDev** [Appsilon/rhino#110]
### Problem
During `init()` we create `.Rprofile` which contains some important settings required to run the app. Without sourcing it the app fails to start:
```r
rhino::init()
shiny::runApp()
## Error in box::use(r/main) : 
##  unable to load module “r/main”
```
Sourcing `.Rprofile`, running `options(box.path = file.path(getwd(), "app"))`, or restarting R sessions fixes this behavior.

### Possible solutions
Source `.Rprofile` after `init()`. This might cause issues, e.g. with renv - we need to test this thoroughly.

Perhaps we should just clearly inform users that they should restart R (maybe in addition to sourcing `.Rprofile`).

**Comment by TymekDev** [comment]
I think this issue is already fixed. I just installed a new {rhino} version, ran `rhino::init()`, and ran `shiny::runApp() within a single R session without any issues.

[Proof on video (Slack link)](https://appsilon.slack.com/archives/C03ER9PCDK9/p1704792206846139)

**Comment by kamilzyla** [comment]
The code example from the issue no longer produces an error because we now `setup_box_path()` in `rhino::app()` (#404).

It is worth noting that R session restart is still recommended (we run `renv::init()` which prints "renv activated -- please restart the R session") and sometimes required:

```r
rhino::init()
rhino::test_r()
# Error in `box::use(app/main[...], )`: unable to load module “app/main”
