### ISSUE TITLE
How-to guide draft: Migrating apps to Rhino

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/rhino#138]

**Comment by jakubnowicki** [comment]
After reading the DIVIO documentation guide, this seems to me that this should be rather a "how-to guide" than a "tutorial".

**Comment by tmakowski** [comment]
I see this how-to guide having a following structure:
- How to prepare your app structure
  - Sanity check: shiny::runAppDir()
  - What if: app uses renv
  - What if: app uses box
    - What if: app has trailing commas and breaks
- Run rhino::init()
  - What if: app had .Rprofile
- How to configure Rhino
  - What if: app used renv
  - What if: app used box

What do you think @kamilzyla @jakubnowicki? Anything you would change?

**Comment by kamilzyla** [comment]
Overall LGTM. Perhaps you don't need "What if: app uses box" in the first step. We can recommend to always start with testing whether `shiny::appDir("app")` works. It is really up to you how you structure the content inside though :slightly_smiling_face: Don't overthink it - I'm sure everything we write will undergo several iterations of improvements anyway.

Useful reference stuff (in case you missed anything):
1. #17
2. #64
3. [Documentation](https://appsilon.github.io/rhino/reference/app.html#legacy-entrypoint-1) of `rhino::app()`.
4. [Notes](https://docs.google.com/document/d/1wctIyriLN4tXT9lUcVF8Q7JvriqrkKKf7ODOvrZWiRg/edit#heading=h.cqce7ri9884a) in our Rhino Documentation doc.
