### ISSUE TITLE
[Conference Backlog] Review Project Board

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/rhino#195]
We have 3 full Sprints left before the conference (2022-04-04 ⟶ 2022-04-25). Let's prepare a Conference Backlog together - a list of tasks to be completed in this time frame.

Please review everything in the Scratchpad and Product Backlog columns of our [Project Board](https://github.com/orgs/Appsilon/projects/3?fullscreen=true) and move what you consider as priority to **Conference Backlog column**. (Alternatively comment here / use labels.) Note that we only have 2 weeks for implementation tasks related to the package - it needs to be ready for CRAN submission on 2022-04-18.

Tick yourself off the list when you're done. Please finish by EOD Wednesday.
* [x] @jakubnowicki 
* [ ] @TymekDev 
* [x] @marekrogala 
* [x] @kamilzyla

**Comment by jakubnowicki** [comment]
Besides the tasks I've added to the conference backlog, I feel a need to discuss at least a little bit those two entries from the scratchpad:
https://github.com/orgs/Appsilon/projects/3#card-80028767
https://github.com/orgs/Appsilon/projects/3#card-79753855

**Comment by kamilzyla** [comment]
Based on Team's input I prepared a proposal for Conference Backlog.
