### ISSUE TITLE
Prepare an implementation plan for "environment config" feature

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/rhino#201]
Discussion notes: [link](https://docs.google.com/document/d/1rIQngtvCYmC2nSDpqyO6dTSXprIJP0Wj_awaMlz7dtM/edit#).

**Comment by kamilzyla** [comment]
## Implementation plan
#### Code
1. Add config package to Rhino dependencies.
2. Add the following `config.yml` to template:
    ```r
    default:
      RHINO_LOG_LEVEL: !expr Sys.getenv("RHINO_LOG_LEVEL", "INFO")
      RHINO_LOG_FILE: !expr Sys.getenv("RHINO_LOG_FILE", NA)
    ```
3. To configure logger in `rhino::app()`, use `config::get("RHINO_LOG_LEVEL")` and `config::get("RHINO_LOG_FILE")`.

#### Documentation
1. “How to: Manage secrets and environments” with the content outlined below.

## User perspective
#### Secrets
1. Define all secrets in `.Renviron`.
2. Store the file in 1Password.
4. Use a separate `.Renviron` for each environment.
5. Swap the whole file when changing environments.
6. Read secrets with `Sys.getenv()`.
7. Recommendation: Use `ALL_CAPS` for variable names.

#### Environments
1. Define environments and their settings to `config.yml`.
2. Set environment via `R_CONFIG_ACTIVE` in `.Renviron`.
4. Each setting must have a default value defined (enforced by the config package).
5. To make a setting overridable with an environment variable, use `!expr Sys.getenv()` in all environments.
8. Import `config` with box and call as usual, e.g:
    ```r
    box::use(config)
    config$get("TRIALS")
    ````
9. Recommendation: Use `ALL_CAPS` for field names. Fits naturally with environment variables.

## Concerns
1. YAGNI. If you need “default” only, you don’t need `config.yml` at all.
3. Config just returns `NULL` for undefined fields.
4. All fields must have a default value, even if it makes little sense.

**Comment by jakubnowicki** [comment]
I'm not sure I will be available on Monday, so please check my review here:

> ## Implementation plan
> #### Code
> 1. Add config package to Rhino dependencies.
> 2. Add the following `config.yml` to template:
>    ```r
>    default:
>      RHINO_LOG_LEVEL: !expr Sys.getenv("RHINO_LOG_LEVEL", "INFO")
>      RHINO_LOG_FILE: !expr Sys.getenv("RHINO_LOG_FILE", NA)
Usage of a log file seems to be a quite specific and rare case. In enterprise environments, logs will be collected via RSConnect and there simply is no need for using of additional log files. I recommend removing this and moving it to the documentation part. Also, since after removal, the config will return NULL for this field, I recommend adding `is.null` check to  onfigure_logger`.
>    ```
> 3. To configure logger in `rhino::app()`, use `config::get("RHINO_LOG_LEVEL")` and `config::get("RHINO_LOG_FILE")`.
> 
> #### Documentation
> 1. “How to: Manage secrets and environments” with the content outlined below.
> 
> ## User perspective
> #### Secrets
> 1. Define all secrets in `.Renviron`.
> 2. Store the file in 1Password.
We shouldn't recommend a specific solution, just a general "keep them in a safe place."
> 3. Use a separate `.Renviron` for each environment.
> 4. Swap the whole file when changing environments.

In general, local `.Renviron` should not be used in the deployment, so IMHO this is just a matter of what suits best for the particular developer.

> 5. Read secrets with `Sys.getenv()`.
> 6. Recommendation: Use `ALL_CAPS` for variable names.
> 
> #### Environments
> 1. Define environments and their settings to `config.yml`.
> 2. Set environment via `R_CONFIG_ACTIVE` in `.Renviron`.
> 3. Each setting must have a default value defined (enforced by the config package).

This is not true, check comment in Concerns section.

> 4. To make a setting overridable with an environment variable, use `!expr Sys.getenv()` in all environments.
> 5. Import `config` with box and call as usual, e.g:
>    ```r
>    box::use(config)
>    config$get("TRIALS")
>    ```
> 6. Recommendation: Use `ALL_CAPS` for field names. Fits naturally with environment variables.

I disagree, those are yaml keys, not env variables so this is misleading. And the convention in yaml is rather to use lowercase.

> 
> ## Concerns
> 1. YAGNI. If you need “default” only, you don’t need `config.yml` at all.
> 2. Config just returns `NULL` for undefined fields.

Any `yaml` configuration will return `NULL`, since it is a behavior of R lists. On the other hand empty environmental variable will return "". I believe `NULL` is more meaningful. 

> 3. All fields must have a default value, even if it makes little sense.

This is not true, `config` allows using environment-specific fields, e.g. this is a valid one:
```yaml
default:
  a: 1

prod:
  b: 2
```

**Comment by kamilzyla** [comment]
Thanks for the comments! I updated the implementation plan:
1. Recommend `snake_case` for `config.yml` fields instead of `CONSTANT_CASE`.
2. Remove notes default field values being mandatory.
3. Make recommendations for `.Renviron` files.
4. Update concerns.

Comments:
1. For consistency, I'd rather keep the `rhino_log_file` in `config.yml`. The documentation will mention that log file is configured via `config::get("rhino_log_file")`. It's easier to understand when you see it in `config.yml` right away.
2. On my `NULL` concerns: The `config$get("field")` returns `NULL` if `field` is not defined, while it could (and IMO should) throw an error instead.

**Comment by marekrogala** [comment]
Looks very good!

>We shouldn't recommend a specific solution, just a general "keep them in a safe place."
Same here. I wouldn't recommend specifically Renviron, but "keep them in a safe place, typically in env vars." "You can manage them with .Renviron files stored in password manager, or other safe ways."

**Comment by kamilzyla** [comment]
I have further updated the plan to emphasise that `.Renviron` is just one way of doing things. This will be part of our documentation, so the exact wording can be refined after 1.0.0 release.

**Comment by kamilzyla** [comment]
Agreed with the team to move forward with the implementation.
