### ISSUE TITLE
Features on a heavily blocked machine (no internet connection, only RSPM mirroring CRAN is available).

### ISSUE THREAD

**Issue by marekrogala** [Appsilon/rhino#210]

**Comment by marekrogala** [comment]
@kamilzyla i don't understand this issue, can you please clarify it?

**Comment by kamilzyla** [comment]
This was a note from @TymekDev to be discussed.

**Comment by TymekDev** [comment]
I felt like what Rhino offered was mostly bound to Node (JS bundling, up-to-date SASS, linting JS, linting SASS, ...) which is not available in certain environments.

**Comment by kamilzyla** [comment]
Moving to #338.
