### ISSUE TITLE
`devtools::document()` erroneously adds `create_module` to exports

### ISSUE THREAD

**Issue by marekrogala** [Appsilon/rhino#212]
It seems that `devtools::document()` simply searches for `#' @export` string in function body, and detects it in a string literal. Whenever we run `devtools::document()`, we'll need to remember to manually remove the `export(create_module)` line from `NAMESPACE`. We might forget to do it at some point.

**Comment by marekrogala** [comment]
@kamilzyla I don't understand how serious this is for us, can you elaborate?

**Comment by kamilzyla** [comment]
Only relevant for developers.
