### ISSUE TITLE
Add spell check to the CI 

### ISSUE THREAD

**Issue by marekrogala** [Appsilon/rhino#215]
### Problem
Spelling mistakes in our documentation can go unnoticed. It looks bad and can delay a CRAN release if such mistakes are found by the CRAN team.

### Goal
Use CI to automatically check the spelling of our documentation (including Roxygen and [Rhino website](https://appsilon.github.io/rhino/)).

### Details
1. Use the [spelling](https://docs.ropensci.org/spelling/reference/spell_check_package.html) package.
2. Run it from `.github/workflows/ci.yml`.
3. Ensure that spelling mistakes anywhere in our documentation cause the CI to fail. Test it on a separate branch and link the results in the PR.

**Comment by vibalre** [comment]
Sample workflow with failed spelling checks: https://github.com/Appsilon/rhino/actions/runs/3240738061

Sample workflow with passed spelling checks because of `inst/WORDLIST`: https://github.com/Appsilon/rhino/actions/runs/3240789835

**Comment by vibalre** [comment]
I think `spelling::spell_check_package()` is already checking all files including those in `man`, but I am not sure how we check the `rhino` website. Is it kept in a different directory, i.e. not in `pkgdown` directory?

**Comment by kamilzyla** [comment]
The `pkgdown` directory contains some config for our website; the actual content is in `vignetttes`.

**Comment by vibalre** [comment]
Thanks. This is good news then, as `spelling:spell_check_package()` already checks `vignettes`.
