### ISSUE TITLE
Hardcoded "root" folder in function calls build_sass() and build_js() does not exist

### ISSUE THREAD

**Issue by baderd** [Appsilon/rhino#276]
### Steps to reproduce

1. Use Windows10 :-)
2. install rhino R package
3. install node.js 64bit installer from [here](https://nodejs.org/dist/v16.15.0/node-v16.15.0-x64.msi)
4. "enable" yarn from windows command-line inside your repository folder with: `corepack enable`
5. Follow the steps of the [rhino tutorial](https://appsilon.github.io/rhino/articles/tutorial/create-your-first-rhino-app.html) until you read `build_sass()`

### What happened?

Described in detail at this [stackoverflow post](https://stackoverflow.com/questions/72273192/problem-with-yarn-dependency-using-the-rhino-r-package).

In brief:
```
>build_sass()
yarn run v1.22.15
$ sass --no-source-map --style=compressed root/app/styles/main.scss:root/app/static/css/app.min.css
Error reading root\app\styles\main.scss: no such file or directory.
error Command failed with exit code 66.
...

> rhino::build_js()
yarn run v1.22.15
warning ..\..\package.json: No license field
$ webpack
assets by status 0 bytes [cached] 1 asset

ERROR in main
Module not found: Error: Can't resolve 'C:\Users\XXX\Documents\workspace\rhino_dummy\.rhino\node\root\app\js\index.js' in 'C:\Users\XXX\Documents\workspace\rhino_dummy\.rhino\node'
resolve 'C:\Users\XXX\Documents\workspace\rhino_dummy\.rhino\node\root\app\js\index.js' in 'C:\Users\XXX\Documents\workspace\rhino_dummy\.rhino\node'
  using description file: C:\Users\XXX\Documents\workspace\rhino_dummy\.rhino\node\package.json (relative path: .)
    
```

### Expected behavior

The directory `...\workspace\rhino_dummy\.rhino\node\root` should either be created automatically or it should become a varible in the respective `build_*()` functions.

### Rhino diagnostics

```
Windows 10 x64 build 19042
R version 4.1.0 (2021-05-18)
rhino: 1.0.0
node: v16.15.0
yarn: 1.22.15
```

**Comment by kamilzyla** [comment]
Hey @baderd, thanks for your report! For Node.js functions to work on Windows 10, you'll need to enable [Developer Mode](https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development#active-developer-mode) on your system as mentioned in our [How-to: Use Rhino on Windows](https://appsilon.github.io/rhino/articles/how-to/use-rhino-on-windows.html) article.

After you do that, please delete the `.rhino/node` directory from your project, or run `rhino:::add_node(clean = TRUE)` in the root of your project.

Let us know if this resolves your issue :slightly_smiling_face:

**Comment by baderd** [comment]
Hi Kamil,
Unfortunately, enabling developer mode is no option for me. I will discuss this internally.

Thank you very much for the explanation! Maybe you can add a more detailed warning message to the package pointing at this issue and explain a bit more in the [How-to: Use Rhino on Windows](https://appsilon.github.io/rhino/articles/how-to/use-rhino-on-windows.html) article. But I guess after the conference your time is rare :-)

You can close the issue.

**Comment by sharingtom** [comment]
> After you do that, please delete the `.rhino/node` directory from your project, or run `rhino:::add_node(clean = TRUE)` in the root of your project.

Ran into a similar issue following along [the workshop](https://youtu.be/8H_ZHUy8Yj4?t=2515). I had missed enabling Developer Mode, but doing so and running `rhino:::add_node(clean = TRUE)` fixed it. Thanks!

May I suggest adding a note to the vignette about having to run `rhino:::add_node(clean = TRUE)` if the user hadn't enabled Developer Mode prior to `rhino::init()` (or is it `rhino::build_js()?`)?

**Comment by dawiegriesel** [comment]
I've tried using rhino:::add_node(clean = TRUE) but it's not an exported function of rhino. Any suggestions getting round this issue?

**Comment by tomasokal** [comment]
I had a similar issue. 

After `rhino:::add_node(clean = TRUE)`, and rerunning `rhino::build_js()`, I was getting an error saying "Cannot find module 'webpack-cli/package.json'"

**Comment by kristianHoden** [comment]
I would have had appreciated a link to the [How-to: Use Rhino on Windows] page in the main tutorial. Now, it took me quite some googling before ending up here.

**Comment by kamilzyla** [comment]
Symbolic links are problematic on Windows; we are going to stop using them (#375).
