### ISSUE TITLE
RStudio complains during push-button deployment

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/rhino#280]
Publishing a Rhino application to RSConnect using the RStudio Publish button fails because the number of files in the project is too large (it scans `.rhino/node/node_modules`):

```
Error in enforceBundleLimits(dir, totalSize, totalFiles) : 
  The directory ~/projects/rhino-app cannot be deployed because it contains too many files (the maximum number of files is 10000). Remove some files or adjust the rsconnect.max.bundle.files option.
Calls: <Anonymous> -> explodeFiles -> enforceBundleLimits
Execution halted
```

RStudio version: 2022.02.2 Build 485
OS: Ubuntu 21.10

**Comment by kamilzyla** [comment]
@jakubnowicki It would be great to get rid of this problem, but you should still be able to deploy: include only `.Rprofile`, `dependencies.R`, `app.R` and the `app` directory. Does it help?

**Comment by jakubnowicki** [comment]
This does not help, since RStudio GUI lists files using the same file limit, so the modal looks similar to this:
![image](https://user-images.githubusercontent.com/7279715/170932532-9e68e0f5-a030-45c6-bc4a-0b7ccd3b2949.png)
