### ISSUE TITLE
With `legacy_entrypoint` at `source` the UI must be a character

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/rhino#283]
Rhino with the `legacy_entrypoint` level set to `source` requires UI as character, not function. In the latter case, the error message is enigmatic and difficult to debug. We need an entry in the documentation.

**Comment by Leszek-Sieminski** [comment]
UI cannot be a function when legacy_entrypoint is on source level.

This main.R won't work (even though it is a proper Shiny app):
```
library(shiny)

ui <- function() {
  bootstrapPage(
    tags$h3(
      "Test"
    )
  )
}

server <- function(input, output, session) {
}
```

On the other hand, this main will work:
```
library(shiny)

ui <- bootstrapPage(
    tags$h3(
      "Test"
    )
  )

server <- function(input, output, session) {
}
```
