### ISSUE TITLE
Setup a Windows machine on AWS for testing

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/rhino#288]
In Appsilon we don't use Windows in general, so it's difficult to test Rhino there. Let's research whether it's viable to have a Windows VM on AWS (ask our infra team) and setup one if so.

**Comment by FMKerckhof** [comment]
I have just started a Rino project on Windows 10 (with Node and yarn) - if there is anything I can test for you feel free to let me know.

**Comment by kamilzyla** [comment]
@FMKerckhof That's very kind of you, thanks! We still need a solution for regular testing though :slightly_smiling_face:

**Comment by kamilzyla** [comment]
I thought about it and figured it will be easier (and won't cost us anything) to use a [Windows virtual machine](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/).
