### ISSUE TITLE
rhino::build_sass() ignores use or import statements for sass modules

### ISSUE THREAD

**Issue by FMKerckhof** [Appsilon/rhino#293]
### Steps to reproduce

The [documentation](https://appsilon.github.io/rhino/reference/build_sass.html) clearly states that `rhino::build_sass()` is used to convert  app/styles/main.scss file into app/static/css/app.min.css. However, if we want to modularize our scss code we'd like to use [@import](https://developer.mozilla.org/en-US/docs/Web/CSS/@import) or [@use](https://css-tricks.com/introducing-sass-modules/) statements, these are not included/parsed into the `app.min.css`

Reprex
---
1. Have a `main.scss` with valid scss code (use `rhino::lint_sass()`) 
2. Add additional scss code in a script stored in subfolder modules (e.g. `modules/_module1.scss`)
3. Add `@import "modules/module1"` at the top of `main.scss`
4. Run `rhino::build_sass() `
5. Observe that no reference to the import can be found in `app.min.css`

### What happened?

Use or import statements in main.scss are ignored (without warning) by `rhino::build_sass()`.
`rhino::linst_sass()` furthermore does not recognize the `@use` statement - related #285 

### Expected behavior

Parsing of the import statements into the minified css 

### Rhino diagnostics

Windows 10 x64 build 19044
R version 4.2.0 (2022-04-22 ucrt)
rhino: 1.0.0
node: v16.15.1
yarn: 1.22.15

### Comments

I am unsure if this behavior is intended, however I wonder what is the best resolution? Should we explicitly put all statements into main.scss? This could potentially lead to a very bulky file.

**Comment by kamilzyla** [comment]
@FMKerckhof Not really :wink: You are speaking of [Sass variables](https://sass-lang.com/documentation/variables), which is another Sass feature which gets compiled away (not to be confused with CSS variables, also mentioned on the page I linked). Just try to use `$orange` in some selector; the reference will be replaced with the `#3c924b` value in the generated CSS.
