### ISSUE TITLE
Rhino initialized Github Actions workflow seem to be failing for the unit test section

### ISSUE THREAD

**Issue by tomasokal** [Appsilon/rhino#308]
### Steps to reproduce

1. Set up project with rhino::init()
2. Tests pass locally
3. Test fails to load modules through Github Actions

### What happened?

Have a basic rhino framework app where the `.github\workflows\rhino-test.yml` file is largely untouched. Only modifications to this were removal of the cypress testing section at end.

Actions are failing at the unit test section as can be seen by these two workflows:

- https://github.com/tomasokal/dfs/runs/7596177350?check_suite_focus=true
- https://github.com/tomasokal/dfs/runs/7604559915?check_suite_focus=true

In both of these cases, the issue is not with the test itself, which passes and when running `rhino::test_r()` locally, encounters no issue, but rather through an error with box. Whether with test-main.R or test-logic-players.R, neither of these test files are able to load their respective modules and get an error like `unable to load module`

Is there a step I am missing here or a section of the documentation I have missed? For further reference, have followed along with https://www.youtube.com/watch?v=8H_ZHUy8Yj4

### Expected behavior

For tests to pass locally and and through Github Actions.

### Rhino diagnostics

Windows 10 x64 build 19043
R version 4.1.0 (2021-05-18)
rhino: 1.1.0
node: v16.13.2
yarn: 1.22.15

### Comments

Very cool framework by the way.

**Comment by kamilzyla** [comment]
Thanks for the report @tomasokal! We'll take a look this week.

**Comment by tomasokal** [comment]
@kamilzyla , I will update this later today as I have a working test now and want to check the difference between the states of the repo between the working and failing tests. 

This is definitely user error on my part, but am hoping can provide a solution to others that may encounter this issue as well as find source and how to prevent.

**Comment by kamilzyla** [comment]
For box to work you'll need to configure [`box.path`](https://klmr.me/box/reference/use.html#search-path). This is normally done in `.Rprofile`, which `rhino::init()` creates for you:
```r
if (file.exists("renv")) {
  source("renv/activate.R")
} else {
  # The `renv` directory is automatically skipped when deploying with rsconnect.
  message("No 'renv' directory found; renv won't be activated.")
}

# Allow absolute module imports (relative to the app root).
options(box.path = getwd())
```

Be sure to commit the `.Rprofile` which Rhino creates for you or include the `options(box.path = getwd())` line in yours.
