### ISSUE TITLE
Support for nested test file structures

### ISSUE THREAD

**Issue by telegott** [Appsilon/rhino#319]
Thanks for this promising package!

It seems that there is more and more momentum behind moving away from the traditional package structure that is fundamentally limited with regards to best practices and is not the most sensible choice in all situations.

A hindrance for working fully "outside" the package structure is the lack of support from some tools, e.g. `testthat`. I checked `rhino`'s code for testing, but the `testthat::test_dir` function only test files in one folder, not in nested ones, which would mean that the `tests/testthat` folder could not mirror the file tree in `R`, which I think would be a standard way to structure things.

Are there plans to work around this limitation, e.g. combining the results of multiple `test_dir` runs?

**Comment by kamilzyla** [comment]
Hey @telegott, thanks for your interest in Rhino!

We are aware of the limitations on tests structure and it's definitely in our plans to find a solution for that. In fact we already have an issue to track it: #39. I'm going to close this one too keep things organized. Thanks for asking!
