### ISSUE TITLE
yarn v2 doesn't support build_sass function

### ISSUE THREAD

**Issue by lightinfection** [Appsilon/rhino#326]
### Steps to reproduce

1.  I install yarn of 2.0 version and my node version is 16.17.1. 
2. When I follow the tutorial to convert ./app/styles/main.scss into ./app/static/css/app.min.css by build_sass() function, there is an ambiguous syntax error for yarn.

### What happened?

#
Ambiguous Syntax Error: Cannot find who to pick amongst the following alternatives:
0. yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--cache-folder #0]
2. yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--cache-folder #0]
While running --cwd .rhino/node install
Error:
! System command 'yarn' exited with status 1.
#

It seems to be an issue with the yarn version. In the devDependencies of the package.json file, yarn("build-sass") used sass of 1.39.0 version. I couldn't find specific supported yarn versions for it, so I changed my yarn version back to v1.22.15 according to https://stackoverflow.com/questions/72273192/problem-with-yarn-dependency-using-the-rhino-r-package, and the build_sass() finally worked.

### Expected behavior

figure out if the yarn v2 is not supported

### Rhino diagnostics

Windows 10 x64 build 19043
R version 4.1.3 (2022-03-10)
rhino: 1.1.1
node: v16.17.1
yarn: 2.0.0-rc.31.git.20200417.3a6076f

**Comment by kamilzyla** [comment]
Thanks for your report @lightinfection and please excuse the late response! Rhino only works with yarn classic (v1). We are not going to add support for v2 - instead we plan to remove the need for yarn completely (#104). Meanwhile we'll need to update our docs so they point to v1 (#360).
