### ISSUE TITLE
Improve UX for users without Node.js

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/rhino#418]
**Part I**: Look at Rhino from the perspective of a user without Node.js (e.g. uninstall Node.js and try all the functions in our [reference](https://appsilon.github.io/rhino/reference/index.html)) and come up with ideas how we could improve their experience.

**Part II**: Implement the ideas (e.g. add warning messages, link to documentation, improve docs).

**Comment by Leszek-Sieminski** [comment]
@kamilzyla as you suggested I started from checking all the functions that rely on Node.js. It seems we have an error with a good description and even a link to external documentation (see the screenshot below).

The questions: 

- is the error message enough?
- (if not) what else could we do to inform user about the need/value of installing Node.js?

![image](https://user-images.githubusercontent.com/32634801/207906972-f7d5eed4-d39c-4ca5-8f22-e175beb8d97f.png)

**Comment by Leszek-Sieminski** [comment]
Idea:

we can inform user after loading the package via `packageStartupMessage()` that more advanced functions require Node, give them a link to the article + inform them how to silence this message (because this can be annoying)

**Comment by Leszek-Sieminski** [comment]
Proposed execution:
![image](https://user-images.githubusercontent.com/32634801/208072923-a7c27309-934d-4c6e-923a-cf68f4118e47.png)

**Comment by kamilzyla** [comment]
After discussion with Leszek we determined that no action is required: the messages for Node.js commands are sufficient and it makes little sense to have startup messages as Rhino won't typically be loaded with `library()`.
