### ISSUE TITLE
build_sass claims to create minified CSS but it's not minified

### ISSUE THREAD

**Issue by daattali** [Appsilon/rhino#490]
The `build_sass()` function creates a `app.min.css` file. The standard convention in the web is that `min.css` files are minified. However, this file is not minified. Minified CSS files generally have all unnecessary whitespace removed, but this file has all line breaks intact.

**Comment by jakubnowicki** [comment]
Thank you for pointing this. The minification works fine for Node version, but it was actually not working for R version of `build_sass`. Fix is in review.
