### ISSUE TITLE
docs: additional note in tutorial to follow up

### ISSUE THREAD

**Issue by jhk0530** [Appsilon/rhino#499]
Hi, thanks for nice work. 

Recently, I'm trying to migrate my shiny application with rhino. (and Following tutorial and videos first)

Even I have node and npm installed. That was not enough to follow tutorial completely. (not only update node / npm with lts)

I think some additional note in [tutorial](https://appsilon.github.io/rhino/articles/tutorial/create-your-first-rhino-app.html) might help to follow it.

1. Install node dependencies to `build_sass()`

Below codes are what I did to follow up tutorial (additionally)

- Install [**dart-sass**](https://github.com/sass/dart-sass) via `brew install sass/sass/sass`

2. install node dependencies to `build_js()`

- Install **webpack** via `npx webpack`
- Install **babel-loader** via `npm install babel-loader`
- Install **@babel/preset-env** via `npm install @babel/preset-env`
- Install **@babel/preset-react** via `npm install @babel/preset-react`

I understand as there is another option to run `build_sass` and `build_js` without install node, but I couldn't find enough explanation for it. 

> If you are not able to install Node in your environment, you can change the sass entry in the rhino.yml file to r.

So maybe, note 

**in rhino.yml**
```
sass: r
```

this will more helpful for newbie like me.

(and there's not existing explanation for `build_js` without node)

If you don't mind, I'd like to make PR in `/vignettes/tutorial/create-your0first-rhino-app.Rmd`

Thanks.

Kim

**Comment by jhk0530** [comment]
Also could write extra note with `rhino[rhinos]` (and following codes)
But I don't think that's not critical one. 
so I left it out.

**Comment by jakubnowicki** [comment]
Hi @jhk0530, thank you for your suggestions. In general, `rhino` does not require manual installation of Node libraries - it should be able to install them when you first call one of the `sass`/`js` functions. If this does not work on your machine, please send us the error message so we can investigate the issue.

**Comment by jhk0530** [comment]
since my macOS works now (after manually installed above packages) 
I tried with windows PC, and Here is installed npm package lists. which doesn't installed anything for rhino yet.

- `electron-forge`
- `npm`

![image](https://github.com/Appsilon/rhino/assets/6457691/df4da3d2-ad92-45ed-898b-552e77f937ce)

and here's error message from Rstudio console.

![image](https://github.com/Appsilon/rhino/assets/6457691/3c045d72-88e7-44c8-a5d6-97a38ae27f90)

it appears while following [tutorial](https://appsilon.github.io/rhino/articles/tutorial/create-your-first-rhino-app.html#add-custom-styles) after running first `build_sass` 

**If you try running the application right now, you will not see any changes. That is because Rhino uses minified app/static/app.min.css for styling. To use it, you will need to build it using the Rhino function:**

**Comment by jakubnowicki** [comment]
Please provide the output of `rhino::diagnostics()`.

**Comment by jhk0530** [comment]
![image](https://github.com/Appsilon/rhino/assets/6457691/cbcf775f-0126-4c57-915d-8ab6e48e25a0)

> rhino::diagnostics()
Windows 10 x64 build 19045
R version 4.3.1 (2023-06-16 ucrt)
rhino: 1.5.0
node: v18.17.1

**Comment by jakubnowicki** [comment]
From what I see (at least on Windows), `build_sass` found an existing `.rhino` directory in the project. I assume, it could be copied  with the project when moving to Windows. Please remove it, and try running `build_sass` again.

**Comment by jhk0530** [comment]
**It worked.** and retrying `build_sass` doesn't generate `.rhino` directory.

So, problem solved without installing any dependencies of node. 

But here's another question. 
If I want to run rhino (and `build_js`, `build_sass`) in another PC (whatever OS), should I remove `.rhino` directory at first?

**Comment by jakubnowicki** [comment]
The best and preferred way of sharing a Rhino application code is to use version control (`git`). In this setup, `.rhino` directory is automatically ignored. If you really need to copy-paste the project directory, you have to manually remove the it.
