### ISSUE TITLE
`RestRserve` REST API support

### ISSUE THREAD

**Issue by dereckmezquita** [Appsilon/rhino#505]
### Motivation

I'm writing a `rhino` app that will have the `shiny` front end. I want to in the same project create REST API that can be accessed from the front end.

So far I'm experimenting myself, just created a `server` folder.

I have been doing research and am now using `RestRserve` rather than `plumber` as it is the better of the two.

1. No extra logic/coding required for multithreading.
1. Better syntax, I dislike the comment syntax of `plumber` `#*`.
1. Even if `plumber` is used with `future`/`promises` thus solving the scaling issue to some extent we are still left with the impossibility of sharing database connections across threads.

### Feature description

Include in the initial `rhino` template a "Hello world" REST API.

I'm still discovering how to even get the front end and the backend communicating.

### Implementation ideas

A simple "Hello world" API that is accessed from the `shiny` app front end.

### Impact

I write apps in `node` + `TypeScript` and this is a pattern I use all the time. I would like to be able to build full stack apps using just `R`.

### Comments

Thank you for `rhino` I believe this is one of those frameworks/packages that helps build `R` into a mature programming language.

**Comment by jakubnowicki** [comment]
Thank you for submitting this idea. Building a REST API is currently beyond the scope of Rhino.
