### ISSUE TITLE
Cant make minimal build_js example sayHello() work

### ISSUE THREAD

**Issue by pietrodito** [Appsilon/rhino#510]
### Steps to reproduce

1. Create rhino project with init()
2. Move to project dir and restart session
3. Follow minmal example: 
```
// index.js
export function sayHello() { console.log('Hello!'); }
```
```
// main.R
box::use(
  shiny[bootstrapPage, div, moduleServer, NS, renderUI, tags, uiOutput],
)

#' @export
ui <- function(id) {
  ns <- NS(id)
  bootstrapPage(
    tags$button("Hello!", onclick = "App.sayHello()")
  )
}

#' @export
server <- function(id) {
  moduleServer(id, function(input, output, session) {})
}
```
4. rhino::build_sass(); rhino::build_js()

### Bug description

When running the app and clicking the button the browser console reports this error:

Uncaught TypeError: App.sayHello is not a function
    onclick http://localhost:8787/p/5e643ee7/:1

### Expected behavior

The console output: "hello"

### Rhino diagnostics

Linux 6.5.5-1-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Sep 23 12:48:15 UTC 2023
R version 4.3.2 (2023-10-31)
rhino: 1.5.0.9000
node: v20.9.0

**Comment by jakubnowicki** [comment]
Hi, can you provide the content of the `app/static/js/app.min.js` file?

**Comment by pietrodito** [comment]
Ok!

When I look from the browser, the content was:
```
var App;App={};
```

But on the disk:
```
var App;(()=>{"use strict";var e={d:(o,r)=>{for(var t in r)e.o(r,t)&&!e.o(o,t)&&Object.defineProperty(o,t,{enumerable:!0,get:r[t]})},o:(e,o)=>Object.prototype.hasOwnProperty.call(e,o),r:e=>{"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})}},o={};function r(){alert("Hello!")}e.r(o),e.d(o,{sayHello:()=>r}),App=o})();
```

The browser was using some cache file I guess.

Do you know how to prevent that? I am using Firefox Developper. Running, a client of RStudio server in one tab, and run the app in another tab with `shiny::runApp( launch.browser = T)`

**Comment by pietrodito** [comment]
Close!

**Comment by pietrodito** [comment]
Close
