### ISSUE TITLE
Cypress test directories 

### ISSUE THREAD

**Issue by mjfrigaard** [Appsilon/rhino#524]
I noticed the folder structure in my `rhino` application is different than the one described in the tutorial [here](https://github.com/Appsilon/rhino/blob/2b210b40c06792e46926c4a8891e96dbfd894b77/vignettes/tutorial/write-end-to-end-tests-with-cypress.Rmd#L149C25-L149C54).

When I create a new rhino application, the `tests/cypress/` folder contains the following: 

```
tests/cypress
└── integration
    └── app.spec.js

2 directories, 1 file
```

The folder structure in the documentation is slightly different: 

```
tests/cypress
└── e2e
    └── app.spec.js

2 directories, 1 file
```

(the folder paths in the test files also reference the `e2e` folder)

Changing `integration` to `e2e` results in the following when attempting to run `rhino::test_e2e()` 

```
Can't run because no spec files were found.

We searched for any files inside of this folder:

/path/to/rhino/app/tests/cypress/integration
```

Thank you for all of your work on `rhino` :) It's an amazing way to build apps!

**Comment by kamilzyla** [comment]
Hey @mjfrigaard, thanks for your report! You are looking at the documentation of a development version of Rhino (see rhino 1.5.0.**9003** in the page header). The directories will be renamed in the next release.

Of course, we should be showing docs for the latest CRAN release instead. I have created a separate issue for that: #527.
