### ISSUE TITLE
Implement `box.linters`

### ISSUE THREAD

**Issue by radbasa** [Appsilon/rhino#582]
Use new `box.linters` package

**Comment by radbasa** [comment]
Migration guide vignette

**Comment by jakubnowicki** [comment]
Writing the migration guide is the responsibility of the person doing the release (https://github.com/Appsilon/rhino/blob/main/.github/CONTRIBUTING.md#release-process). Please update NEWS.md with information on how to perform the migration part related to your change (`box.linters`). All information from the NEWS.md will be compiled in the release process.
