### ISSUE TITLE
Ensure functions which require Node provide useful feedback if it's not available

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/rhino#59]
To close this task:
1. Most functions: "Do you have Node.js and yarn installed? [link to documentation]".
2. `build_sass()`: "Install yarn or use `sass: r`. [link to documentation]".

Additional things to consider:
1. Write messages as if recommending a colleague what to do with the issue.
2. Consider other functions which could send user to the documentation.

**Comment by jakubnowicki** [comment]
Note after checking migration progress with Marcin: This is a must-have, users are extremely confused when Node is not available.
